import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

await mkdir('site', { recursive: true });
await build({
  entryPoints: { app: 'src/light-entry.js' },
  bundle: true,
  format: 'iife',
  platform: 'browser',
  target: ['chrome100', 'edge100', 'firefox100', 'safari15'],
  outdir: 'site',
  entryNames: '[name]',
  minify: true,
  sourcemap: false,
  legalComments: 'none',
  logLevel: 'info',
});

let html = await readFile('legacy.html', 'utf8');
html = html
  .replace('<title>zhengyifan的简历</title>', '<title>ZhengYifan · 立体作品展</title>')
  .replace('</head>', '    <link rel="stylesheet" href="./site/app.css" />\n  </head>')
  .replace('<body class="relative">', `<body class="relative">
    <canvas id="planet-stage" aria-hidden="true"></canvas>
    <div class="gallery-vignette" aria-hidden="true"></div>
    <div class="exhibition-hud" aria-hidden="true"><strong>CURATED DIGITAL EXHIBITION</strong>SHENZHEN / 2026<br>SPACE 22°32′N · 114°03′E</div>`)
  .replaceAll(' autoplay', '')
  .replace('</body>', '    <script defer src="./site/app.js"></script>\n</body>');

await writeFile('index.html', `<!-- Generated by npm run build:static. Layout source: legacy.html -->\n${html}`, 'utf8');
console.log('\nEditorial exhibition ready: index.html');
